---
title: "Coffee Ratings"
author: "Joshua Cook"
date: "July 7, 2020"
output: github_document
---

## Setup

TidyTuesday link: https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-07-07/readme.md

```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "#>", dpi = 400)

library(mustashe)
library(glue)
library(magrittr)
library(ggtext)
library(ggforce)
library(patchwork)
library(tidyverse)
library(conflicted)

conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("setdiff", "dplyr")

blue <- "#5eafe6"
red <- "#eb5e60"
light_grey <- "grey80"
grey <- "grey50"
dark_grey <- "grey25"

theme_set(theme_minimal())

# To shutup `summarise()`.
options(dplyr.summarise.inform = FALSE)

set.seed(0)
```

## Data

```{r}
coffee_ratings <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-07/coffee_ratings.csv") %>%
    janitor::clean_names() %>%
    mutate(id = row_number())
```

## EDA

```{r}
naniar::miss_var_summary(coffee_ratings)
```

```{r}
coffee_ratings %>%
    select(id, total_cup_points, aroma:moisture) %>%
    pivot_longer(-id) %>%
    ggplot(aes(value)) +
    facet_wrap(~ name, ncol = 3, scales = "free") +
    geom_density(size = 1, color = blue, fill = blue, alpha = 0.2) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.01)))
```

```{r}
coffee_ratings %>%
    select(id, aroma:moisture) %>%
    pivot_longer(-id) %>%
    ggplot(aes(x = name, y = value)) +
    ggbeeswarm::geom_quasirandom(size = 0.4, alpha = 0.2, color = blue) +
    geom_boxplot(outlier.shape = NA, size = 1, alpha = 0.2, fill = grey) +
    scale_y_continuous(expand = expansion(mult = c(00.02, 0.02)))
```

## Modeling

- model `total_cup_points` on other features of coffee 
- logistic: species ~ aroma:sweetness
- logistic: two countries ~ aroma:sweetness

```{r}
library(rstanarm)
library(bayestestR)
library(bayesplot)
library(see)
library(tidybayes)
library(modelr)
```

```{r}
d <- coffee_ratings %>%
    filter(!is.na(country_of_origin) & !is.na(harvest_year))

stash("cupping_by_beantype", depends_on = "d", {
    cupping_by_beantype <- stan_glm(
        total_cup_points ~ 1 + species + country_of_origin,
        data = d,
        family = gaussian(link = "identity"),
        prior_intercept = normal(location = 0, scale = 2, autoscale = FALSE),
        prior = normal(location = 0, scale = 0.5, autoscale = FALSE),
        cores = 4,
        refresh = 0
    )
})

stash("cupping_by_beantype_me", depends_on = "d", {
    cupping_by_beantype_me <- stan_glmer(
        total_cup_points ~ 1 + species + country_of_origin + (1|harvest_year),
        data = d,
        family = gaussian(link = "identity"),
        prior_intercept = normal(location = 0, scale = 2, autoscale = FALSE),
        prior = normal(location = 0, scale = 0.5, autoscale = FALSE),
        cores = 4,
        refresh = 0
    )
})

```

```{r}
cupping_by_beantype_loo <- loo(cupping_by_beantype)
cupping_by_beantype_me_loo <- loo(cupping_by_beantype_me)
loo_compare(cupping_by_beantype_loo, cupping_by_beantype_me_loo)
```

```{r}
plot(bayestestR::hdi(cupping_by_beantype, ci = c(0.5, 0.75, 0.89, 0.95)))
```
```{r}
d %>%
    modelr::data_grid(species, country_of_origin) %>%
    add_predicted_draws(cupping_by_beantype, n = 50) %>%
    ggplot(aes(x = .prediction, y = country_of_origin)) +
    geom_boxplot(aes(color = species, fill = species), alpha = 0.2, outlier.shape = NA)
```

### Logisitic regression on processing method

```{r}
washed_wet_d <- coffee_ratings %>%
    filter(!is.na(processing_method)) %>%
    filter(processing_method %in% c("Natural / Dry", "Washed / Wet")) %>%
    mutate(washed_wet = processing_method == "Washed / Wet") %>%
    select(washed_wet, species, aroma:sweetness, -clean_cup)

stash("processing_method_model", depends_on = "washed_wet_d", {
    processing_method_model <- stan_glmer(
        washed_wet ~ aroma + flavor + aftertaste + acidity + 
                     body + balance + uniformity + sweetness + 
                     (1|species),
        data = washed_wet_d,
        family = binomial(link = "logit"),
        prior_intercept = normal(0, 3, autoscale = FALSE),
        prior = normal(0, 3, autoscale = FALSE),
        refresh = 0,
        cores = 4
    )
})
```

```{r}
plot(processing_method_model)
```

```{r}
as.data.frame(describe_posterior(processing_method_model))
```

```{r}
plot(bayestestR::hdi(processing_method_model, 
                     ci = c(0.5, 0.75, 0.89, 0.95), 
                     effects = "all"))
```

```{r}
pp_check(processing_method_model)
```

```{r}
pp_check(processing_method_model, plotfun = "hist")
```

```{r}
washed_wet_averages <- washed_wet_d %>%
    summarise(aroma = median(aroma), 
              flavor = median(flavor), 
              aftertaste = median(aftertaste), 
              acidity = median(acidity),
              body = median(body), 
              balance = median(balance), 
              uniformity = median(uniformity), 
              sweetness = median(sweetness))

n_draws <- 100
pred_range <- seq(5.5, 9.5, length.out = 100)

pred_data_acidity <- washed_wet_d %>%
    data_grid(washed_wet, species, 
              acidity = pred_range) %>%
    bind_cols(washed_wet_averages %>% select(-acidity)) %>%
    add_fitted_draws(processing_method_model, n = n_draws) %>%
    add_column(var = "acidity")

pred_data_body <- washed_wet_d %>%
    data_grid(washed_wet, species, 
              body = pred_range) %>%
    bind_cols(washed_wet_averages %>% select(-body)) %>%
    add_fitted_draws(processing_method_model, n = n_draws) %>%
    add_column(var = "body")

bind_rows(pred_data_acidity, pred_data_body) %>%
    mutate(x_value = ifelse(var == "acidity", acidity, body)) %>%
    ggplot(aes(x = x_value, y = .value)) +
    geom_line(aes(group = paste(.draw, .iteration, species, var), 
                  color = species),
              alpha = 0.15) +
    geom_text(aes(x = x, y = y, label = label),
               data = tibble(x = 5.46, 
                             y = c(0.1, 0.9), 
                             label = c("acidity", "body")),
               family = "Arial", size = 5, color = "grey40", fontface = "italic", hjust = 1) +
    geom_text(aes(x = x, y = y, label = label),
               data = tibble(x = median(pred_range), 
                             y = c(0, 1), 
                             label = c("Natural / Dry", "Washed / Wet")),
               family = "Arial", size = 6, color = "grey15", fontface = "bold") +
    scale_x_continuous(limits = c(4.7, 9.5), expand = c(0, 0)) +
    scale_color_brewer(palette = "Dark2") +
    labs(x = "score",
         y = "predicted processing style",
         title = "Associations between bean preparation and metrics of taste.")
```
