---
title: "Palmer Penguins"
author: "Joshua Cook"
date: "July 28, 2020"
output: github_document
---
    
## Setup
    
TidyTuesday link: [2020/2020-07-28/readme.md](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-07-28/readme.md)

```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "#>", dpi = 400)

library(mustashe)
library(glue)
library(magrittr)
library(Rtsne)
library(see)
library(bayestestR)
library(ggeffects)
library(lme4)
library(rstanarm)
library(patchwork)
library(tidyverse)
library(conflicted)

conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("setdiff", "dplyr")

blue <- "#5eafe6"
dark_blue <- "#408ec2"
red <- "#eb5e60"
light_grey <- "grey80"
grey <- "grey50"
dark_grey <- "grey25"

theme_set(theme_minimal())

# To shut-up `summarise()`.
options(dplyr.summarise.inform = FALSE)

set.seed(0)
```

## Data

```{r}
penguins <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-28/penguins.csv") %>%
    janitor::clean_names() %>%
    na.omit()
```

## EDA

```{r}
penguins %>%
    count(species) %>%
    ggplot(aes(x = species, y = n)) +
    geom_col()
```

```{r}
penguins %>%
    select(species, bill_length_mm:body_mass_g) %>%
    pivot_longer(-species, names_to = "measurement", values_to = "value") %>%
    ggplot(aes(x = value)) +
    facet_wrap(~ measurement, ncol = 2, scales = "free") +
    geom_density(aes(color = species, fill = species), size = 1.2, alpha = 0.2) +
    scale_color_brewer(palette = "Set1") +
    scale_fill_brewer(palette = "Set1")
```

```{r}
set.seed(123)

scale_nums <- function(x) {
    (x - mean(x)) / sd(x)
}

tsne_data <- penguins %>% 
    select(bill_length_mm:body_mass_g) %>%
    mutate_all(scale_nums)
penguins_tsne <- Rtsne(tsne_data, pca = FALSE)

penguins_tsne$Y %>%
    as.data.frame() %>%
    as_tibble() %>%
    set_names(c("z1", "z2")) %>%
    mutate(species = penguins$species,
           sex = penguins$sex) %>%
    ggplot(aes(z1, z2)) +
    geom_point(aes(color = species)) +
    scale_color_brewer(palette = "Set1") +
    labs(title = "t-SNE of penguin data")
```

## Modeling

```{r}
d <- penguins %>%
    mutate(male = sex == "male") %>%
    select(male, species, bill_length_mm:body_mass_g) %>%
    mutate_if(is.numeric, scale_nums) %>%
    mutate(male = as.numeric(male))
sex_log_m1 <- glm(male ~ ., 
                  data = d,
                  family = binomial(link = "logit"))

summary(sex_log_m1)
```

```{r}
ggpredict(sex_log_m1, "bill_depth_mm [all]") %>%
    plot()
```

```{r}
ggpredict(sex_log_m1, c("bill_depth_mm [all]", "bill_length_mm")) %>%
    plot()
```

```{r}
ggpredict(sex_log_m1, c("bill_depth_mm [all]", "species")) %>%
    plot()
```


```{r}
ggpredict(sex_log_m1, 
          c("body_mass_g [all]", "bill_length_mm", "bill_depth_mm", "flipper_length_mm")) %>%
    plot()
```

```{r}
sex_log_m2 <- glmer(
    male ~ 1 + body_mass_g + bill_length_mm + bill_depth_mm + flipper_length_mm + (1|species), 
    data = d,
    family = binomial(link = "logit")
)

summary(sex_log_m1)
```

```{r}
bind_rows(
    ggpredict(sex_log_m1, "body_mass_g [all]") %>% as_tibble() %>% add_column(effects = "FE"),
    ggpredict(sex_log_m2, "body_mass_g [all]") %>% as_tibble() %>% add_column(effects = "ME")
) %>%
    ggplot(aes(x, predicted)) +
    geom_ribbon(aes(ymin = conf.low, ymax = conf.high, fill = effects), alpha = 0.2) +
    geom_line(aes(group = effects, color = effects), size = 1.3) +
    scale_color_brewer(palette = "Set2") +
    scale_fill_brewer(palette = "Set2")
```

```{r}
d <- penguins %>%
    select(sex, species, island, bill_length_mm:body_mass_g) %>%
    mutate(sex = factor(sex),
           species = factor(species),
           island = factor(island),
           bill_length_mm = scale_nums(bill_length_mm),
           bill_depth_mm = scale_nums(bill_depth_mm),
           flipper_length_mm = scale_nums(flipper_length_mm))

bm_model1 <- glm(
    body_mass_g ~ 1 + sex + species + bill_length_mm + bill_depth_mm + flipper_length_mm,
    data = d,
    family = gaussian(link = "identity")
)

bm_model2 <- glm(
    body_mass_g ~ 1 + sex * species + bill_length_mm + bill_depth_mm + flipper_length_mm,
    data = d,
    family = gaussian(link = "identity")
)

bm_model3 <- glm(
    body_mass_g ~ 1 + (sex + bill_length_mm + bill_depth_mm + flipper_length_mm) * species,
    data = d,
    family = gaussian(link = "identity")
)

bm_model4 <- glm(
    body_mass_g ~ 1 + (bill_length_mm + bill_depth_mm + flipper_length_mm) * (sex + species),
    data = d,
    family = gaussian(link = "identity")
)

summary(bm_model1)
```

```{r}
p1 <- ggpredict(bm_model1, c("sex", "species")) %>%
    plot() +
    ggtitle("Fixed Effects model")
p2 <- ggpredict(bm_model2, c("sex", "species")) %>%
    plot() +
    ggtitle("Fixed Effects model\nwith interaction")
(p1 | p2 | guide_area()) +
    plot_layout(widths = c(5, 5, 1), guides = "collect")
```
```{r}
ggpredict(bm_model3, c("bill_length_mm", "sex", "species")) %>%
    plot()
```

```{r}
ggpredict(bm_model4, c("bill_length_mm", "sex", "species")) %>%
    plot()
```

```{r}
bm_model4_stan <-  stan_glm(
    body_mass_g ~ 1 + (bill_length_mm + bill_depth_mm + flipper_length_mm) * (sex + species),
    data = d,
    family = gaussian(link = "identity")
)
```

```{r}
plot(bm_model4_stan)
```

```{r}
plot(bayestestR::hdi(bm_model4_stan, ci = c(0.5, 0.75, 0.89, 0.95)))
```

```{r}
p1 <- ggpredict(bm_model4, c("bill_length_mm [all]", "sex", "species")) %>%
    plot() +
    ggtitle("Frequentist")
p2 <- ggpredict(bm_model4_stan, c("bill_length_mm [all]", "sex", "species")) %>%
    plot() +
    ggtitle("Bayesian")

(p1 | p2 | guide_area()) +
    plot_layout(widths = c(5, 5, 1), guides = "collect")
```

```{r}
ggpredict_plot_factory <- function(m, x_axis, x_axis_title, include_y_axis = TRUE) {
    ggpredict(m, c(x_axis, "sex", "species")) %>%
    plot() +
    theme(
        legend.title = element_blank(),
        legend.position = "right",
        plot.title = element_blank(),
        plot.subtitle = element_blank()
    ) +
    labs(x = x_axis_title,
         y = ifelse(include_y_axis, "predicted body mass (g)", ""))
}

p1 <- ggpredict_plot_factory(bm_model4_stan, "bill_length_mm [all]", "bill length (scaled)", include_y_axis = FALSE)
p2 <- ggpredict_plot_factory(bm_model4_stan, "bill_depth_mm [all]", "bill depth (scaled)")
p3 <- ggpredict_plot_factory(bm_model4_stan, "flipper_length_mm [all]", "flipper length (scaled)", include_y_axis = FALSE)

((p1 / p2 / p3) | guide_area()) +
    plot_layout(widths = c(5, 1), guides = "collect") +
    plot_annotation(title = "Predicted effect of body measurements on the body mass of penguins",
                    subtitle = "Including interaction terms for sex and species of penguin")

ggsave(file.path("2020-07-28_palmer-penguins_files", 
                 "bodymass_by_measurements.png"), 
       width = 6, height = 10)
```
