---
title: "Caribou Location Tracking"
author: "Joshua Cook"
date: "June 23, 2020"
output: github_document
---

## Setup

TidyTuesday link: https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-06-23/readme.md

```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "#>", cache = TRUE, dpi = 400)

library(mustashe)
library(glue)
library(magrittr)
library(lubridate)
library(easystats)
library(rstanarm)
library(tidybayes)
library(patchwork)
library(tidyverse)
library(conflicted)

conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("setdiff", "dplyr")

blue <- "#5eafe6"
red <- "#eb5e60"
light_grey <- "grey80"
grey <- "grey50"
dark_grey <- "grey25"

theme_set(theme_minimal())

# To shutup `summarise()`.
options(dplyr.summarise.inform = FALSE)

memoise_cache <- memoise::cache_filesystem("./.memoise")

set.seed(0)
```

## Data

```{r}
caribou_indiv <- read_csv(
    "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-23/individuals.csv"
) %>%
    janitor::clean_names()

caribou_indiv
```

```{r}
naniar::miss_var_summary(caribou_indiv)
```

```{r}
caribou_locations <- read_csv(
    "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-23/locations.csv"
) %>%
    janitor::clean_names()

caribou_locations
```

```{r}
naniar::miss_var_summary(caribou_locations)
```

```{r}
n_distinct(caribou_locations$animal_id)
```

```{r}
caribou_locations %>%
    count(animal_id, sort = TRUE)
```

## Data preparation

```{r}
# Get the distance between each longitude and latitude point (in meters).
get_distance_between_event <- function(lng, lat) {
    dist_traveled <- c(0)
    for (i in seq(2, length(lat))) {
        d <- geosphere::distm(c(lng[[i-1]], lat[[i-1]]),
                              c(lng[[i]], lat[[i]]),
                              fun = geosphere::distHaversine)
        dist_traveled <- c(dist_traveled, d)
    }
    return(dist_traveled)
}
get_distance_between_event <- memoise::memoise(get_distance_between_event,
                                               cache = memoise_cache)


caribou_locations %<>%
    arrange(animal_id, timestamp) %>%
    group_by(animal_id) %>%
    filter(n() > 1) %>%
    mutate(dist_traveled = get_distance_between_event(longitude, latitude)) %>%
    ungroup()
```


```{r}
# The duration (in hours) between each successive timestamp value.
get_duration_between_event <- function(ts) {
    as.numeric(ts - dplyr::lag(ts, n = 1, default = ts[[1]])) / (1810800)
}
get_duration_between_event <- memoise::memoise(get_duration_between_event,
                                               cache = memoise_cache)


caribou_locations %<>%
    arrange(animal_id, timestamp) %>%
    group_by(animal_id) %>%
    mutate(diff_in_timestamp = get_duration_between_event(timestamp)) %>%
    ungroup()
```

```{r}
caribou_locations %<>%
    mutate(speed = dist_traveled / diff_in_timestamp)
```


## EDA

```{r}
caribou_locations %>%
    group_by(animal_id) %>%
    slice(-1) %>%
    ungroup() %>%
    select(event_id, dist_traveled, diff_in_timestamp, speed) %>%
    pivot_longer(-event_id) %>%
    ggplot(aes(log10(value))) +
    facet_wrap(~ name, nrow = 3, scales = "free") +
    geom_histogram(aes(color = name, fill = name), size = 1.2, alpha = 0.2, bins = 100) +
    scale_fill_brewer(palette = "Dark2") +
    scale_color_brewer(palette = "Dark2") +
    theme(axis.title.x = element_blank(),
          legend.title = element_blank(),
          legend.position = "none") +
    labs(title = "Distributions of computed values",
         x = "value (log10-transformed)",
         y = "count")
```

```{r}
summary(caribou_locations$diff_in_timestamp)
mean_reading_duration <- mean(caribou_locations$diff_in_timestamp)
```


```{r}
top_bottom_fastest_caribou <- caribou_locations %>%
    filter(diff_in_timestamp >= mean_reading_duration) %>%
    group_by(animal_id) %>%
    slice(-1) %>%
    filter(n() > 100) %>%
    summarise(avg_speed = mean(speed)) %>%
    ungroup() %>%
    arrange(avg_speed)
top_bottom_fastest_caribou <- bind_rows(
    head(top_bottom_fastest_caribou),
    tail(top_bottom_fastest_caribou)
)

caribou_locations %>%
    filter(animal_id %in% top_bottom_fastest_caribou$animal_id) %>%
    group_by(animal_id) %>%
    slice(-1) %>%
    ungroup() %>%
    mutate(animal_id = fct_reorder(animal_id, speed, .fun = median)) %>%
    ggplot(aes(animal_id, log10(speed))) +
    geom_violin(fill = "white") +
    geom_boxplot(width = 0.1, outlier.shape = NA, fill = light_grey, color = dark_grey) +
    theme(axis.text.x = element_text(angle = 35, hjust = 1)) +
    labs(x = "animal ID",
         y = "speed (meters / hour; log10-transformed)",
         title = "The 10 fastest and slowest caribou",
         subtitle = glue("Only inlcuding caribou with at least 100 measurements of at least {round(mean_reading_duration, 2)} of an hour."))
```

```{r}
caribou_locations %>%
    group_by(animal_id) %>%
    slice(-1) %>%
    filter(n() >= 50) %>%
    summarise(avg_speed = mean(speed)) %>%
    ungroup() %>%
    ggplot(aes(log10(avg_speed))) +
    geom_density(color = grey, fill = grey, size = 1.2, alpha = 0.2) +
    labs(x = "average speed (meters / hour; log10-transformed)",
         y = "density",
         title = "Distribution of average speeds.",
         subtitle = "Only including caribous with at least 50 measurements.")
```

```{r}
caribou_locations %>%
    distinct(animal_id, study_site) %>%
    count(animal_id) %>%
    filter(n > 1)
```


## Modeling

Model the speed of the caribou with and without varying intercepts.

```{r}
d <- caribou_locations %>%
    group_by(animal_id) %>%
    slice(-1) %>%
    filter(n() >= 50) %>%
    ungroup() %>%
    select(animal_id, event_id, season, dist_traveled, diff_in_timestamp, speed) %>%
    mutate(event_id = as.character(event_id),
           summer = as.numeric(season == "Summer"),
           speed = log10(speed)) %>%
    filter(is.finite(speed))

# Sample 10 caribou randomly.
sample_caribou <- d %>%
    count(animal_id) %>%
    filter(n > 1e3) %>%
    sample_n(10) %>%
    jhcutils::u_pull(animal_id)
    
# Sample 1/4 of the data points for each of the 10 random caribou.
d <- d %>% 
    filter(animal_id %in% !!sample_caribou) %>%
    group_by(animal_id) %>%
    sample_frac(0.1) %>%
    ungroup()
```

```{r}
naniar::miss_var_summary(d)
```

With a single global intercept.

```{r}
stash("caribou_speed_m1", depends_on = "d", {
    caribou_speed_m1 <- stan_glm(
        speed ~ 1 + summer,
        data = d,
        prior_intercept = normal(),
        prior = normal(),
        cores = 1
    )
})

summary(caribou_speed_m1)
```

With varying intercepts for each caribou.

```{r}
stash("caribou_speed_m2", depends_on = "d", {
    caribou_speed_m2 <- stan_lmer(
        speed ~ 1 + summer + (1 | animal_id),
        data = d,
        prior_intercept = normal(),
        prior = normal(),
        prior_aux = exponential(),
        prior_covariance = decov(),
        cores = 1
    )
})

summary(caribou_speed_m2)
```

Compare the two models using leave-one-out cross validation.

```{r}
caribou_speed_m1_loo <- loo(caribou_speed_m1, cores = 1)
caribou_speed_m2_loo <- loo(caribou_speed_m2, cores = 1)
loo_compare(list(caribou_speed_m1_loo, caribou_speed_m2_loo))
```

Highest density intervals 

```{r}
m1_hdi_plot <- plot(bayestestR::hdi(caribou_speed_m1, ci = c(0.5, 0.75, 0.89, 0.95))) +
    theme(legend.position = "none") +
    labs(title = "HDI with a single intercept")
m2_hdi_plot <- plot(bayestestR::hdi(caribou_speed_m2, ci = c(0.5, 0.75, 0.89, 0.95))) +
    theme(legend.position = "right") +
    labs(title = "HDI with varying intercepts")

(
    m1_hdi_plot | m2_hdi_plot | guide_area()
) +
    plot_layout(widths = c(3, 3, 1), guides = "collect")
```

```{r}
caribou_pal <- randomcoloR::randomColor(n_distinct(d$animal_id), 
                                        luminosity = "dark")
names(caribou_pal) <- sort(unique(d$animal_id))

caribou_speed_m2 %>%
    spread_draws(b[term,group]) %>%
    mutate(group = str_remove(group, "animal_id\\:")) %>%
    group_by(term, group, .iteration) %>%
    mutate(avg_b = mean(b)) %>%
    ungroup() %>%
    ggplot(aes(x = .iteration, y = avg_b)) +
    geom_line(aes(group = group, color = group), alpha = 0.7) +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = expansion(mult = c(0.02, 0.02))) +
    scale_color_manual(values = caribou_pal) +
    theme(legend.position ="bottom") +
    labs(x = "sampling iteration (averaged across 4 chains)",
         y = "sampled coefficient value",
         title = "MCMC sampling chains for 10 caribou",
         subtitle = "Each line represents the Markov Chain Monte Carlo samples for the varying intercepts\nof the 10 caribou used for this Bayesian linear modeling.",
         color = "caribou ID")
```

```{r}
post <- d %>%
    modelr::data_grid(animal_id, summer) %>%
    add_fitted_draws(caribou_speed_m2)

post %>%
    mutate(summer = ifelse(summer == 1, "summer", "winter")) %>%
    ggplot(aes(x = summer, y = .value)) +
    facet_wrap(~ animal_id, nrow = 1) +
    geom_boxplot(aes(color = animal_id, fill = animal_id),
                 alpha = 0.2, outlier.shape = NA, notch = TRUE) +
    scale_color_manual(values = caribou_pal, guide = FALSE) +
    scale_fill_manual(values = caribou_pal, guide = FALSE) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    labs(x = "season",
         y = "posterior predicted speed",
         title = "The posterior predictions for the speed of each caribou",
         subtitle = "Hiow fast each caribou is expected to travel in each season.")
```

